POST http://localhost:3005/register
Content-Type: application/json

{
    "username": "selva_1201",
    "email": "selva.mern12@gmail.com",
    "password": "selva@1201"
}

###

POST http://localhost:3005/login
Content-Type: application/json

{
    "email": "selva.mern12@gmail.com",
    "password": "selva@1201"
}

###
POST http://localhost:3005/job/add
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3YmY5ZDcwMS1jZmY1LTQyODUtYjUyYS00OGRmMjMzMmQxMjkiLCJpYXQiOjE3NDE3ODk5MDMsImV4cCI6MTc0MjY1MzkwM30.k0N2Zm-Y91r6Lm4c7CzzRlt2ubSfQdRkp23TNPa4GMY

  {
    "user_id": "7bf9d701-cff5-4285-b52a-48df2332d129",
    "company_name": "Mahindra & Mahindra",
    "logo_url": "https://upload.wikimedia.org/wikipedia/commons/e/e0/Mahindra_%26_Mahindra_Logo.svg",
    "job_position": "Automobile Engineer",
    "monthly_salary": "₹85,000",
    "job_type": "Full-time",
    "remote_office": "Office",
    "location": "Chennai, Tamil Nadu",
    "job_description": "Design and develop automobile components, work on electric vehicle technology.",
    "about_company": "Mahindra & Mahindra is India's top automobile manufacturer.",
    "skills_required": "Automobile Engineering, CAD, MATLAB, EV Technology",
    "additional_info": "Experience in electric vehicle development preferred.",
    "job_posted": "13-03-2025"
  }
###
[,,,,
]


###

GET http://localhost:3005/job/get

###

PUT http://localhost:3005/job/update/fecaf1c2-ffa4-4bf9-9d76-51c5a34b3f9d
Content-Type: application/json

{"job_posted" : "10-03-2025"}

###

DELETE http://localhost:3005/job/delete/612b9141-e56d-474c-92d3-6ebabc158092